[package]
name = "haven-db"
version.workspace = true
edition.workspace = true

[dependencies]
rusqlite = { workspace = true }
haven-types = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
